use_frameworks!

platform :ios, '15.6'

target 'MyPodLibrary_Example' do
  pod 'MyPodLibrary', :path => '../'

  target 'MyPodLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
